stages:
  - test

playwright_regress:
  stage: test
  timeout: 2h
  tags:
    - docker
  image: mcr.microsoft.com/playwright:v1.58.2-jammy

  variables:
    PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: "1"
    PLAYWRIGHT_BROWSERS_PATH: "/ms-playwright"

  before_script:
  - node -v
  - npm -v
  - npm ci
  # npx playwright install --with-deps  # обычно лишнее в официальном образе
  - curl -fsSL -o allurectl https://github.com/allure-framework/allurectl/releases/download/2.18.0/allurectl_linux_amd64
  - chmod +x allurectl
  - ./allurectl --version

  script:
  - echo "Branch=${Branch:-main} Browser=${Browser:-chromium} Grep=${Grep:-@regress}"

  # Просто логируем доступность Allure (не валим job)
  - curl -vk --connect-timeout 10 --max-time 30 "$ALLURE_ENDPOINT/api/uaa/account/me" || true

  # Запуск тестов + отправка результатов в Allure TestOps
  - ./allurectl watch --results ./allure-results -- npx playwright test -c playwright.config.ts --project="${Browser:-chromium}" --grep "${Grep:-@regress}"

  artifacts:
    when: always
    expire_in: 7 days
    paths:
      - allure-results/