stages:
  - test

playwright_regress:
  stage: test
  image: mcr.microsoft.com/playwright:v1.50.0-jammy
  variables:
    # чтобы не падало из-за лишних загрузок/телеметрии
    PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: "1"
  before_script:
    - node -v
    - npm -v

    # Установка зависимостей (используем package-lock.json)
    - npm ci

    # Если браузеры не входят/нужно переустановить:
    - npx playwright install --with-deps

    # Скачать allurectl под Linux (amd64)
    - curl -fsSL -o allurectl https://github.com/allure-framework/allurectl/releases/latest/download/allurectl_linux_amd64
    - chmod +x allurectl
    - ./allurectl --version

  script:
    # Важно: ALLURE_* переменные должны быть в GitLab CI/CD Variables
    - ./allurectl watch -- npx playwright test --grep @regress

  artifacts:
    when: always
    paths:
      - allure-results/
      - playwright-report/
    expire_in: 7 days